<?xml version="1.0" encoding="utf-8"?><Database Name="AutoTest" Class="AutoTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PC59;Initial Catalog=AutoTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AutoTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Device" Member="Devices">
    <Type Name="Device">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Test" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>